In [2]:
import numpy as np  
import matplotlib.pyplot as plt  
import pandas as pd  

In [3]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# Assign colum names to the dataset
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

# Read dataset to pandas dataframe
dataset = pd.read_csv(url, names=names)

In [4]:
dataset.head()  

sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [5]:
X = dataset.iloc[:, :-1].values  
y = dataset.iloc[:, 4].values

In [6]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)  

In [7]:
from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler()  
scaler.fit(X_train)

X_train = scaler.transform(X_train)  
X_test = scaler.transform(X_test)  


In [8]:
#distance=[]
length=len(X_test)-1
length

29

In [54]:
dist=[]
for x in range(len(X_train)):
    dist.append([])
    for y in range(length):
        distance=(X_train[x]-X_test[y])**2
        dist[x].append(distance)

In [55]:
dist[0]

[array([0.38422295, 0.26356731, 0.62883343, 0.6031947 ]),
 array([0.        , 0.06589183, 0.028875  , 0.06702163]),
 array([6.14756723, 0.26356731, 5.93220924, 6.04870239]),
 array([2.59734715, 0.59302645, 2.16883367, 1.67554083]),
 array([0.38422295, 0.59302645, 0.08020835, 0.06702163]),
 array([0.13832026, 0.26356731, 0.        , 0.82101501]),
 array([3.01230794, 3.22869955, 5.13333412, 3.76996686]),
 array([0.06147567, 2.37210579, 0.38820839, 0.6031947 ]),
 array([3.01230794, 4.21707697, 1.41487522, 2.0274044 ]),
 array([ 0.75307699, 16.86830786,  5.39320916,  4.84231299]),
 array([3.45800657, 6.58918276, 0.20533336, 0.01675541]),
 array([0.01536892, 0.06589183, 0.15720836, 0.15079867]),
 array([1.24488236, 1.05426924, 1.03950016, 1.67554083]),
 array([ 2.2131242 , 11.13571886,  5.39320916,  6.70216331]),
 array([0.01536892, 0.26356731, 0.05133334, 0.01675541]),
 array([3.01230794, 4.21707697, 5.65950087, 6.04870239]),
 array([0.24590269, 0.06589183, 0.38820839, 0.6031947 ]),
 array

In [56]:
def sum_list(items):
    sum_numbers = 0
    for x in items:
        sum_numbers += x
    return sum_numbers

In [73]:
distance=[]
for x in range(29):
    a=sum_list(dist[0][x])
    a=a**(1/2)
    distance.append(a)

In [74]:
distance

[1.3710646920247191,
 0.4022293687748481,
 4.2885948944225065,
 2.652309954644353,
 1.06041472016685,
 1.105849256620857,
 3.891568896415322,
 1.850671379793025,
 3.2667513718174526,
 5.277964285420721,
 3.204571437391345,
 0.6239132772727295,
 2.2392392886485646,
 5.044225959801522,
 0.5890882598407019,
 4.35173392590122,
 1.141576807502913,
 4.722471905168608,
 1.3396358581285706,
 4.307718263399983,
 1.2331046232588652,
 4.379811422819869,
 4.279724452397,
 1.7344003122217815,
 0.8643109721239502,
 1.430270020674615,
 4.498922035921324,
 2.338107427493649,
 1.1279410708699489]

In [75]:
dictionary=[]
for x in range (29):
    dictionary.append(distance[x])
#distance.sort()
dictionary

[1.3710646920247191,
 0.4022293687748481,
 4.2885948944225065,
 2.652309954644353,
 1.06041472016685,
 1.105849256620857,
 3.891568896415322,
 1.850671379793025,
 3.2667513718174526,
 5.277964285420721,
 3.204571437391345,
 0.6239132772727295,
 2.2392392886485646,
 5.044225959801522,
 0.5890882598407019,
 4.35173392590122,
 1.141576807502913,
 4.722471905168608,
 1.3396358581285706,
 4.307718263399983,
 1.2331046232588652,
 4.379811422819869,
 4.279724452397,
 1.7344003122217815,
 0.8643109721239502,
 1.430270020674615,
 4.498922035921324,
 2.338107427493649,
 1.1279410708699489]

In [76]:
distance.sort()

In [77]:
distance
#k=input("Number of nearest neighbours")''

[0.4022293687748481,
 0.5890882598407019,
 0.6239132772727295,
 0.8643109721239502,
 1.06041472016685,
 1.105849256620857,
 1.1279410708699489,
 1.141576807502913,
 1.2331046232588652,
 1.3396358581285706,
 1.3710646920247191,
 1.430270020674615,
 1.7344003122217815,
 1.850671379793025,
 2.2392392886485646,
 2.338107427493649,
 2.652309954644353,
 3.204571437391345,
 3.2667513718174526,
 3.891568896415322,
 4.279724452397,
 4.2885948944225065,
 4.307718263399983,
 4.35173392590122,
 4.379811422819869,
 4.498922035921324,
 4.722471905168608,
 5.044225959801522,
 5.277964285420721]

In [78]:
dictionary


[1.3710646920247191,
 0.4022293687748481,
 4.2885948944225065,
 2.652309954644353,
 1.06041472016685,
 1.105849256620857,
 3.891568896415322,
 1.850671379793025,
 3.2667513718174526,
 5.277964285420721,
 3.204571437391345,
 0.6239132772727295,
 2.2392392886485646,
 5.044225959801522,
 0.5890882598407019,
 4.35173392590122,
 1.141576807502913,
 4.722471905168608,
 1.3396358581285706,
 4.307718263399983,
 1.2331046232588652,
 4.379811422819869,
 4.279724452397,
 1.7344003122217815,
 0.8643109721239502,
 1.430270020674615,
 4.498922035921324,
 2.338107427493649,
 1.1279410708699489]

In [83]:
k=2#Number of nearest neighbours

for x in range(k):
    for y in range(29):
        if(distance[x]==dictionary[y]):
            print("The nearest item is at position",y)

The nearest item is at position 1
The nearest item is at position 14
